"""
Combines correctness (pytest) results + performance results into a final
weighted score, and posts it as a comment on the triggering PR.

Weighting: 60% correctness, 40% performance.

Requires env vars (already available in GitHub Actions):
    GITHUB_TOKEN, GITHUB_REPOSITORY, GITHUB_EVENT_PATH

Usage:
    python grading/combine_and_post.py
"""

import json
import os
import xml.etree.ElementTree as ET

import requests

REPO_ROOT = os.path.join(os.path.dirname(__file__), "..")
JUNIT_PATH = os.path.join(REPO_ROOT, "results.xml")
PERF_PATH = os.path.join(REPO_ROOT, "outputs", "performance_result.json")

CORRECTNESS_WEIGHT = 0.6
PERFORMANCE_WEIGHT = 0.4


def parse_pytest_results():
    tree = ET.parse(JUNIT_PATH)
    root = tree.getroot()
    suite = root if root.tag == "testsuite" else root.find("testsuite")
    total = int(suite.attrib.get("tests", 0))
    failures = int(suite.attrib.get("failures", 0))
    errors = int(suite.attrib.get("errors", 0))
    passed = total - failures - errors
    pass_rate = passed / total if total else 0
    return {"total": total, "passed": passed, "pass_rate": pass_rate}


def build_comment(correctness, perf, final_score):
    return f"""## 🤖 Autograder Report — Linear Regression Lab

**Final Score: {final_score:.1f} / 100**

| Component | Result | Weight |
|---|---|---|
| Code correctness | {correctness['passed']}/{correctness['total']} tests passed ({correctness['pass_rate']*100:.0f}%) | 60% |
| Model performance | R² = {perf['r2']}, MSE = {perf['mse']} → {perf['performance_score']}/100 | 40% |

_This is an automated comment generated by the MLS autograder._
"""


def post_comment(body):
    token = os.environ.get("GITHUB_TOKEN")
    repo = os.environ.get("GITHUB_REPOSITORY")
    event_path = os.environ.get("GITHUB_EVENT_PATH")

    if not (token and repo and event_path):
        print("Not running in GitHub Actions context — skipping comment post.")
        print(body)
        return

    with open(event_path) as f:
        event = json.load(f)

    pr_number = event.get("pull_request", {}).get("number") or event.get("number")
    if not pr_number:
        print("No PR number found in event payload — skipping comment post.")
        print(body)
        return

    url = f"https://api.github.com/repos/{repo}/issues/{pr_number}/comments"
    headers = {"Authorization": f"token {token}", "Accept": "application/vnd.github+json"}
    resp = requests.post(url, headers=headers, json={"body": body})
    resp.raise_for_status()
    print(f"Posted comment to PR #{pr_number}")


def main():
    correctness = parse_pytest_results()
    with open(PERF_PATH) as f:
        perf = json.load(f)

    final_score = (
        correctness["pass_rate"] * 100 * CORRECTNESS_WEIGHT
        + perf["performance_score"] * PERFORMANCE_WEIGHT
    )

    comment = build_comment(correctness, perf, final_score)
    post_comment(comment)


if __name__ == "__main__":
    main()
